--- #Version 0.1.0
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - state:
  tasks:
    - include_vars: vars/vars.yml
    - include_vars: vars/secrets.yml
    - include_role:
        name: "{{state}}"
