---
#Version 1.0.0
- name: Shutdown {{backup_nas_hostname}}
  uri:
    url: https://{{backup_nas_hostname}}/api/v2.0/system/shutdown
    user: "{{backup_nas_username}}"
    password: "{{backup_nas_password}}"
    method: POST
    body: >
      {
        "delay": 0
      }
    force_basic_auth: yes
    status_code: 200
    body_format: json
  ignore_errors: yes

- name: "Update vm states"
  become: no
  vmware_vm_info:
    hostname: "{{esx_hostname}}"
    username: "{{esx_username}}"
    password: "{{esx_password}}"
    validate_certs: yes
    vm_type: vm
    show_attribute: yes
  delegate_to: localhost
  register: vm_info

- set_fact:
    powered_vms: []

- set_fact:
    powered_vms: "{{powered_vms}} + ['{{item.guest_name}}']"
  with_items: "{{vm_info.virtual_machines}}"
  when:
    - "item.power_state != 'poweredOff'"
    - item.guest_name not in infrastructure
# ####################################
# Enter Phase 1 (Graceful VM shutdown)
# ####################################
- include_tasks:
    file: onbattery-phase1-vm-shutdown-loop.yml
  loop: "{{range(1, 10) | list}}"
  loop_control:
    loop_var: round
  when:
    - powered_vms|length > 0

- name: "Update vm states"
  become: no
  vmware_vm_info:
    hostname: "{{esx_hostname}}"
    username: "{{esx_username}}"
    password: "{{esx_password}}"
    validate_certs: yes
    vm_type: vm
    show_attribute: yes
  delegate_to: localhost
  register: vm_info

- set_fact:
    powered_vms: []

- set_fact:
    powered_vms: "{{powered_vms}} + ['{{item.guest_name}}']"
  with_items: "{{vm_info.virtual_machines}}"
  when:
    - "item.power_state != 'poweredOff'"
    - item.guest_name not in infrastructure

# ####################################
# Enter Phase 2 (Forceful VM poweroff)
# ####################################

- include_tasks:
    file: onbattery-phase2-vm-poweroff-loop.yml
  loop: "{{range(1, 3) | list}}"
  loop_control:
    loop_var: round
  when:
    - powered_vms|length > 0

# #####################################
# Enter Phase 3 (Graceful NAS shutdown)
# #####################################

- include_tasks:
    file: onbattery-phase3-nas-shutdown.yml
